[versions]
agp = "8.8.0"
appcompat = "1.7.0"
material = "1.12.0"
layout = "2.2.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "layout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

